filename_base: "cache_before_cuts_SR2"
data_type: [neutron_generator, neutron_generaror, AmBe]
data_type_for_filename: NeutronGenerator

official_cuts_to_apply:
  - 'lax.lichens.sciencerun1.LowEnergyBackground()'
  - 'lax.lichens.sciencerun1.LowEnergyNG()'

pax_settings:
  pax_version: '6.10.1'
  minitrees_to_load:
    - 'Corrections'
    - 'Basics'
    - 'Fundamentals'
    - 'Extended'
    - 'LargestPeakProperties'
    - 'TotalProperties'
    - 'Proximity'
    - 'FlashIdentification'
    - 'TailCut'
    - 'PatternReconstruction'
    - 'CorrectedDoubleS1Scatter'

  tags_to_exclude:
    - 'MVoff,blinded'
    - 'NG,MVoff'
    - 'Noise'
    - 'blinded,MVoff'
    - 'blinded,earthquake'
    - 'blinded,flash'
    - 'blinded,messy,PMTtrip,MVoff,flash'
    - 'blinded,messy,flash'
    - 'messy'
    - 'messy,flash'
    - 'messy,flash,pmttrip'
    - 'messy,pmttrip,flash'
    - 'messy,pmttrip,flash,ramping'
    - 'noise'
    - 'test'
    - 'trip,messy'
    - 'distillation'
    - 'Flash'

  tags_to_include:
    - "NG"
    - "sciencerun0"
    - "sciencerun1"
    - "sciencerun2"

  preselection:
    - 'cs1<500'
    - 's2>200'
    - 'cs1 > 0'
    - 'cs2 > 0'
    - 'drift_time > -1'
