filename_base: "cache_before_cuts_SR1"
outdir: "/home/twolf/scratch-midway2"
data_type: [Rn220, rn220]
data_type_for_filename: Rn220
official_cuts_to_apply:
  - 'lax.lichens.sciencerun1.LowEnergyBackground()'
  - 'lax.lichens.postsr1.S2Width_HE()'
  - 'lax.lichens.postsr1.CS2AreaFractionTopExtended()'
  - 'lax.lichens.postsr1.S2SingleScatter_HE()'
  - 'lax.lichens.postsr1.S1AreaFractionTop_he()'
  - 'lax.lichens.postsr1.PosDiff_HE()'
custom_cuts_to_apply: []

pax_settings:
  pax_version: '6.10.1'
  minitrees_to_load:
    - 'Corrections'
    - 'Basics'
    - 'Fundamentals'
    - 'Extended'
    - 'LargestPeakProperties'
    - 'TotalProperties'
    - 'Proximity'
    - 'FlashIdentification'
    - 'TailCut'
    - 'PatternReconstruction'
    - 'CorrectedDoubleS1Scatter'

  tags_to_exclude:
    - 'Flash'
    - 'flash'
    - 'SourceOpening'
    - 'lowrate'
    - 'LED'
    - 'bad'
    - 'messy'
    - 'test'
    - 'nofield'
    - 'lowfield'
    - 'ramping'
    - 'commissioning'
    - 'pmttrip'
    - 'trip'
    - '_pmttrip'
    - 'SourceMoving'

  tags_to_include:
    - '*sciencerun1'


  preselection:
    # - 'cs1<500'
    - 's2>200'
    - 'cs1 > 0'
    - 'cs2 > 0'
    - 'drift_time > -1'
